# Generated by Django 5.2.1 on 2025-05-12 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate_Record", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="id",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(
                help_text="Unique phone number (12 digits).",
                max_length=15,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 12 digits and start with 6, 7, 8, or 9.",
                        regex="^[6-9]\\d{11}$",
                    )
                ],
            ),
        ),
    ]
