# Generated by Django 5.2.1 on 2025-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Candidate_Record", "0002_remove_candidate_id_alter_candidate_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
